---

- name: Start container
  docker_container:
    name: unifi-controller
    image: jacobalberty/unifi:5.10.25
    restart_policy: unless-stopped
    memory: 2G
    ports:
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 3478:3478
      - 6789:6789
      - 10001:10001
