---

- name: Create required directories
  file: path=/data/unifi/video state=directory

- name: Start container
  docker_container:
    name: unifi-controller
    image: jacobalberty/unifi:latest
    restart_policy: unless-stopped    
    memory: 2G
    ports:
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
 
