---

- name: Create required directories
  file: path=/data/unifi/video state=directory
- name: Create required directories
  file: path=/data/unifi/logs state=directory
- name: Create required directories
  file: path=/data/unifi/cache state=directory
- name: Copy system properties
  copy: content="system.properties" dest=/data/unifi/video/system.properties mode="u+r"

- name: Start container
  docker_container:
    name: unifi-video
    image: pducharme/unifi-video-controller:3.10.6
    restart_policy: unless-stopped
    memory: 2G
    ports:
      - 6666:6666
      - 7080:7080
      - 7443:7443
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - /data/unifi/video:/var/lib/unifi-video
      - /data/unifi/logs:/var/log/unifi-video
      - /data/unifi/cache:/var/cache/unifi-video
