---

- name: Create required directories
  file: path=/data/unifi/video state=directory
- name: Create required directories
  file: path=/data/unifi/logs state=directory
- name: Create required directories
  file: path=/data/unifi/cache state=directory
- name: Copy system properties
  copy: content="system.properties" dest=/data/unifi/video/system.properties mode="u+r"

- name: Start container
  docker_container:
    name: unifi-video
    image: pducharme/unifi-video-controller:3.10.6
    restart_policy: unless-stopped
    memory: 2G
    ports:
      - 1935:1935
      - 6666:6666
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
      - 10002:10001
    volumes:
      - UnifiVideoDataVolume:/var/lib/unifi-video
      - UnifiVideoDataVolume:/var/lib/unifi-video/videos
    # env:
    #    PUID: "1100"
    #    PGID: "1101"
    capabilities:
      - SYS_ADMIN
      - DAC_READ_SEARCH
