# Instack knockd
# - name: Install dependencies
#   yum: name={{ item }} state=present
#   with_items:
#   - 'iptables-persistent'
#   - 'knockd'

# Copies the key from the user who is running ansible to the remote machine
- user: name={{ item.name }} shell=/bin/bash groups=wheel append=yes
  with_items: "{{ ssh_users }}"

- name: Add ssh user keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: "{{ ssh_users }}"

- name: Allow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication yes"
              state=present
  notify: restart sshd

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: restart sshd