---
# Handler for the nginx.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart nginx
  become: true
  service: name=nginx state=restarted

- name: restart firewalld
  become: true
  service: name=firewalld state=restarted
