- name: Hi
  shell: ls

- name: Install Docker py
  pip: name=docker-py==1.9.0
  
# - name: Create a data container
#   docker_container:
#     name: mydata
#     image: busybox
#     volumes:
#       - /data