---
galaxy_info:
  author: Ferran Basora
  description: Enable port knocking for your server
  license: BSD
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
      - precise
      - trusty
      - xenial

  categories:
    - networking
    - system

dependencies: []
