---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to worktajm-nginx-

- hosts: rancher-servers
  # max_fail_percentage: 0
  # serial: 1
  become: yes
  roles:
  - geerlingguy.repo-epel
  - docker-python
  - docker-bash-aliases
  - mongodb-cluster

- hosts: graylog-servers
  become: yes
  roles:
  - { role: docker-containers-graylog,        tags: [ 'setup', 'graylog' ] }    

- hosts: unifi-servers
  # max_fail_percentage: 0
  # serial: 1
  become: yes
  roles:
  - { role: docker-container-unifi-video,  tags: [ 'setup', 'install', 'video', 'unifi'] }
  - { role: docker-container-unifi-controller,  tags: [ 'setup', 'install', 'controller', 'unifi'] }  



