---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to worktajm-nginx-

- hosts: rancher-servers
  # max_fail_percentage: 0
  # serial: 1
  become: yes
  roles:
  - { role: geerlingguy.repo-epel,                  tags: [ 'stage' ]}
  - { role: cchurch.virtualenv,                     tags: [ 'stage' ]}
  - { role: docker-python,                          tags: [ 'stage' ] }
  - { role: docker-bash-aliases,                    tags: [ 'stage' ] }

- hosts: graylog-servers
  become: yes
  roles:
  - { role: docker-containers-graylog,              tags: [ 'setup', 'graylog' ] }    

- hosts: unifi-servers
  become: yes
  roles:
  - { role: docker-container-unifi-video,           tags: [ 'setup', 'install', 'unifi-video' ] }
  - { role: docker-container-unifi-controller,      tags: [ 'setup', 'install', 'unifi-controller' ] }

- hosts: hazelcast-servers
  become: yes
  roles:
  - { role: docker-container-hazelcast,             tags: [ 'setup', 'install', 'controller', 'hazelcast' ] }

- hosts: hazelcast-mmc-servers
  become: yes
  roles:
  - { role: docker-container-hazelcast-mmc,         tags: [ 'setup', 'install', 'controller', 'hazelcast-mmc' ] }

- hosts: smtp-servers
  become: yes
  roles:
  - { role: docker-container-smtp,                   tags: [ 'install', 'smtp' ] }

- hosts: rancher-server-servers
  become: yes
  roles:
  - { role: docker-container-glance,                 tags: [ 'install', 'glance' ] }

- hosts: nginx-servers
  become: yes
  roles:
  - { role: docker-container-nginx,                  tags: [ 'install', 'nginx' ] }
