---
# This playbook deploys the whole application stack in this site.  

# Apply common configuration to worktajm-nginx-

- hosts: worktajm-nginx-servers
  max_fail_percentage: 0
  # serial: 1
  become: yes
  vars:
    timezone: UTC
    fail2ban_config_bantime: 86400
    fail2ban_config_maxretry: 1
    fail2ban_config_ignoreip: 127.0.0.1/8,90.229.133.143
  roles:
    - geerlingguy.repo-epel
    # - sshd
    # - selinux
    # - favorite-yum-packages
    # - role: ntp
      # ntp_config_server: [3.se.pool.ntp.org, 2.se.pool.ntp.org, 1.se.pool.ntp.org, 0.se.pool.ntp.org]
    - nginx-worktajm
    - resmo.fail2ban
    # - ntp

