---

- name: Start container
  docker_container:
    name: glance
    image: nicolargo/glances
    restart_policy: unless-stopped    
    memory: 1G
    ports:
      - "61208:61208"
      - "61209:61209"
    pid_mode: host
    env: 
      GLANCES_OPT: "-w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
 