
- name: Create conf directory for Hazelcast
  file: path=/opt/hazelcast/conf state=directory

- name: Apply template for Hazelcast configuration
  template: src=hazelcast.xml dest=/opt/hazelcast/hazelcast.xml mode="u+r"
  register: hazelcast_config

# - name: Create lib directory for Hazelcast
#   file: path=/opt/hazelcast/lib state=directory

- name: Remove Hazelcast container since configuration was changed
  docker_container:
    name: hazelcast
    state: absent
  when: hazelcast_config.changed

- name: Start Hazelcast
  docker_container:
    name: hazelcast
    image: hazelcast/hazelcast:3.5.4     
    restart_policy: unless-stopped    
    env: 
      JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/hazelcast.xml"
    volumes:
      - /opt/hazelcast/hazelcast.xml:/opt/hazelcast/hazelcast.xml  
    networks:
      - name: "{{docker_network}}"
    ports:
      - "5701:5701"

